/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/jichuang/SDRV4_2_1/td/al_ip/sd.v
 ** Date	:	2022 07 18
 ** TD version	:	5.6.53426
\************************************************************/

`timescale 1ns / 1ps

module sd (  );


endmodule