/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Project/anlogic/ethernet/ip/iddr.v
 ** Date	:	2022 06 18
 ** TD version	:	5.5.47752
\************************************************************/

`timescale 1ns / 1ps

module iddr ( q1, q0, d, clk, rst );
output 		q1;
output 		q0;
input  		d;
input  		clk;
input  		rst;

		EG_LOGIC_IDDR #(
		.ASYNCRST("ENABLE"),
		.PIPEMODE("PIPED"))
		iddr (
		.q1(q1),
		.q0(q0),
		.clk(clk),
		.d(d),
		.rst(rst));

endmodule