/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Project/anlogic/SDRV4_1/rtl/ip/ramfifo.v
 ** Date	:	2022 06 28
 ** TD version	:	5.6.53426
\************************************************************/

`timescale 1ns / 1ps

module ramfifo (
	rst,
	di, re, clk, we,
	do,
	empty_flag,full_flag,rdusedw,wrusedw
 
);

	input rst;
	input [9:0] di;
	input clk, we;
	input re;

	output [9:0] do;
	output empty_flag;
	output full_flag;
	output [15:0] rdusedw;
	output [15:0] wrusedw;

EG_LOGIC_RAMFIFO #(
 	.DATA_WIDTH(10),
	.ADDR_WIDTH(15),
	.SHOWAHEAD(0),
	.IMPLEMENT("AUTO")
)
logic_ramfifo(
	.rst(rst),
	.di(di),
	.clk(clk),
	.we(we),
	.do(do),
	.re(re),
	.empty_flag(empty_flag),
	.full_flag(full_flag),
	.rdusedw(rdusedw),
	.wrusedw(wrusedw)
);

endmodule