--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/Project/anlogic/SDRV4_1/rtl/ip/ramfifo.vhd
 -- Date	:	2022 06 28
 -- TD version	:	5.6.53426
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY ramfifo IS
PORT (
	di	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	do	: OUT STD_LOGIC_VECTOR(9 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	rdusedw			: OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
	wrusedw			: OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END ramfifo;

ARCHITECTURE struct OF ramfifo IS

	BEGIN
	inst : EG_LOGIC_RAMFIFO
		GENERIC MAP (
			DATA_WIDTH			=> 10,
			ADDR_WIDTH			=> 15,
			SHOWAHEAD			=> 0,
			IMPLEMENT			=>"AUTO"
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clk	=> clk,
			we	=> we,
			re	=> re,
			do	=> do,
			empty_flag	=> empty_flag,
			full_flag	=> full_flag,
			rdusedw		=> rdusedw,
			wrusedw		=> wrusedw
		);

END struct;
