/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/Project/anlogic/SDRV4_1/rtl/ip/rom.v
 ** Date	:	2022 06 29
 ** TD version	:	5.6.53426
\************************************************************/

`timescale 1ns / 1ps

module tri_rom ( doa, addra, clka, rsta );

	output [9:0] doa;

	input  [1:0] addra;
	input  clka;
	input  rsta;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(10),
				.ADDR_WIDTH_A(2),
				.DATA_DEPTH_A(4),
				.DATA_WIDTH_B(10),
				.ADDR_WIDTH_B(2),
				.DATA_DEPTH_B(4),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../../sin14bit_16384.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({10{1'b0}}),
				.dib({10{1'b0}}),
				.addra(addra),
				.addrb({2{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule