--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	D:/Project/anlogic/SDRV4_1/rtl/ip/rom.vhd
 -- Date	:	2022 06 29
 -- TD version	:	5.6.53426
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY tri_rom IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(9 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(1 DOWNTO 0);
	clka		: IN STD_LOGIC;
	rsta		: IN STD_LOGIC
	);
END tri_rom;

ARCHITECTURE struct OF tri_rom IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 10,
			ADDR_WIDTH_A	=> 2,
			DATA_DEPTH_A	=> 4,
			DATA_WIDTH_B	=> 10,
			ADDR_WIDTH_B	=> 2,
			DATA_DEPTH_B	=> 4,
			MODE			=> "SP",
			REGMODE_A	=> "NOREG",
			IMPLEMENT	=> "9K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "../../sin14bit_16384.mif",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea		=> '1',
			ceb		=> '0',
			clka		=> clka,
			clkb		=> '0',
			web		=> '0',
			rsta		=> rsta,
			rstb		=> '0',
			doa		=> doa,
			dob		=> OPEN,
			ocea		=> '0',
			oceb		=> '0'
		);

END struct;
